# Generated by Django 5.2.7 on 2025-10-10 13:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Title')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('M', 'Transferred to manager'), ('R', 'Transferred to the restaurant'), ('C', 'Handed over to the courier'), ('P', 'Processed')], db_index=True, default='M', max_length=1, verbose_name='Статус')),
                ('address', models.TextField(verbose_name='Delivery address')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Is Draft')),
                ('order_note', models.TextField(blank=True, max_length=200, verbose_name='Order Note')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registered at')),
                ('called_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Called at')),
                ('delivered_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Delivered at')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=50, unique=True, verbose_name='E-mail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
