# Generated by Django 5.2.7 on 2025-10-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_cakecategory_cake_category_orderelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, verbose_name='Delivery address'),
        ),
    ]
