# Generated by Django 5.2.7 on 2025-10-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0007_remove_order_name_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='called_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='registered_at',
        ),
    ]
