# Generated by Django 5.2.7 on 2025-10-14 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0008_remove_order_called_at_remove_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('M', 'Transferred to manager'), ('R', 'Transferred to the restaurant'), ('C', 'Handed over to the courier'), ('P', 'Processed')], db_index=True, default='D', max_length=1, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='cake',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cake.ingredient', verbose_name='Category'),
        ),
    ]
