# Generated by Django 5.2.7 on 2025-10-14 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0009_ingredient_alter_order_status_cake_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='cake',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='cake.ingredient', verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cake.ingredient', verbose_name='Ingredient'),
        ),
    ]
