# Generated by Django 5.2.7 on 2025-10-14 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0010_size_cake_size_alter_cake_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='cake.size', verbose_name='Size'),
        ),
    ]
